"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
   HoveredLink,
   Menu,
   MenuItem,
   ProductItem,
} from "./components/ui/navbar-menu";
import { useState } from "react";
import { cn } from "../../utils/cn";
import { FloatingNav } from "./components/ui/floating-navbar";
import { IconHome, IconMessage, IconUser } from "@tabler/icons-react";
import { NavbarDemo } from "./components/ui/navbar-menu";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <div className="relative w-full flex items-center justify-center">
               <FloatingNavDemo />
            </div>
            {children}
         </body>
      </html>
   );
}

export function FloatingNavDemo() {
   const navItems = [
      {
         name: "Home",
         link: "/",
         icon: (
            <IconHome className="h-4 w-4 text-neutral-500 dark:text-white" />
         ),
      },
      {
         name: "Contact",
         link: "/privacypolicy",
         icon: (
            <IconUser className="h-4 w-4 text-neutral-500 dark:text-white" />
         ),
      },

      {
         name: "About",
         link: "/termsandconditions",
         icon: (
            <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />
         ),
      },

      {
         name: "FAQ",
         link: "/termsandconditions",
         icon: (
            <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />
         ),
      },
   ];
   return (
      <div className="relative  w-full">
         <FloatingNav navItems={navItems} />
         <DummyContent />
      </div>
   );
}
const DummyContent = () => {
   return <></>;
};
